language: node_js
sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
before_install:
  - npm install -g node-gyp
  - node-gyp install
node_js:
  - "6"
  - "6.3.0"