// Generated by CoffeeScript 1.10.0
(function() {
  var Constants;

  Constants = Constants || {};

  Constants.gateway = {
    PacketCodes: {},
    PacketTypes: {}
  };

  Constants.voice = {
    PacketCodes: {
      IDENTIFY: 0,
      SELECT_PROTOCOL: 1,
      READY: 2,
      HEARTBEAT: 3,
      SESSION_DESC: 4,
      SPEAKING: 5
    }
  };

  module.exports = Constants;

}).call(this);

//# sourceMappingURL=constants.js.map
