// Generated by CoffeeScript 1.10.0
(function() {
  var ObjectID, async, express, globals, request, router, uid;

  express = require('express');

  router = express.Router();

  ObjectID = require('mongodb').ObjectID;

  globals = require('../../models/globals.coffee');

  request = require('request');

  async = require('async');

  uid = require('rand-token').uid;


  /*
    MUSIC ENDPOINT
  
    https://mb.lolstat.net/api/music/
  
    Contains Endpoints:
    - play
    - stop
    - pause
    - resume
    - skip
    - prev
  
    Authentication Required: false
    API Key Required: true
   */

  router.get("/play", function(req, res) {
    var response;
    globals.songComplete(true);
    globals.wss.broadcast(JSON.stringify({
      type: 'playUpdate',
      status: 'play'
    }));
    response = {
      code: 200,
      status: "OK"
    };
    res.set(response);
    return res.end(JSON.stringify(response));
  });

  router.get("/stop", function(req, res) {});

  router.get("/pause", function(req, res) {});

  router.get("/resume", function(req, res) {});

  router.get("/skip", function(req, res) {});

  router.get("/prev", function(req, res) {});

}).call(this);

//# sourceMappingURL=music.js.map
