// Generated by CoffeeScript 1.10.0
(function() {
  var MongoClient,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MongoClient = require('mongodb').MongoClient;

  exports.Playlist = (function() {
    function Playlist() {
      this.db = bind(this.db, this);
    }

    Playlist.prototype.createDBConnection = function(cb) {
      return MongoClient.connect('mongodb://localhost:27017/motorbot', function(err, db) {
        if (err) {
          throw new Error("Failed to connect to database, exiting");
        }
        return cb(db);
      });
    };

    Playlist.prototype.db = function(cb) {
      return this.createDBConnection(function(db) {
        return cb(db);
      });
    };

    return Playlist;

  })();

}).call(this);

//# sourceMappingURL=playlist.js.map
